apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: propagate-name
  annotations:
    config.kubernetes.io/local-config: "true"
# This function runs in the Kptfile pipeline BEFORE interface-fn.
# It copies the cluster name from the WorkloadCluster resource into the
# SrsRanDeployment name suffix and into the "owner" annotations on Interface
# and Capacity resources so that interface-fn can resolve the correct IPAM pool.
replacements:
  - source:
      kind: WorkloadCluster
      name: workload-cluster
      fieldPath: spec.clusterName
    targets:
      # Update the SrsRanDeployment name: "srsran-<clusterName>"
      - select:
          kind: SrsRanDeployment
        fieldPaths:
          - metadata.name
        options:
          delimiter: "-"
          index: 1
      # Update the owner annotation on Interface resources
      - select:
          kind: Interface
        fieldPaths:
          - metadata.annotations.[specializer.nephio.org/owner]
        options:
          delimiter: "."
          index: 4   # replaces the instance name portion only
      # Update the owner annotation on Capacity
      - select:
          kind: Capacity
        fieldPaths:
          - metadata.annotations.[specializer.nephio.org/owner]
        options:
          delimiter: "."
          index: 4
