//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The Nephio Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.
// Regenerate with: make generate

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *SrsRanDeployment) DeepCopyInto(out *SrsRanDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of SrsRanDeployment.
func (in *SrsRanDeployment) DeepCopy() *SrsRanDeployment {
	if in == nil {
		return nil
	}
	out := new(SrsRanDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *SrsRanDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of SrsRanDeploymentList into out.
func (in *SrsRanDeploymentList) DeepCopyInto(out *SrsRanDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SrsRanDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of SrsRanDeploymentList.
func (in *SrsRanDeploymentList) DeepCopy() *SrsRanDeploymentList {
	if in == nil {
		return nil
	}
	out := new(SrsRanDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *SrsRanDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of SrsRanDeploymentSpec into out.
func (in *SrsRanDeploymentSpec) DeepCopyInto(out *SrsRanDeploymentSpec) {
	*out = *in
	out.SliceIntent = in.SliceIntent
	out.Topology = in.Topology
	in.Interfaces.DeepCopyInto(&out.Interfaces)
}

// DeepCopy creates a deep copy of SrsRanDeploymentSpec.
func (in *SrsRanDeploymentSpec) DeepCopy() *SrsRanDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(SrsRanDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of InterfacesSpec into out.
func (in *InterfacesSpec) DeepCopyInto(out *InterfacesSpec) {
	*out = *in
	out.N3 = in.N3
	out.F1 = in.F1
	if in.SBA != nil {
		in, out := &in.SBA, &out.SBA
		*out = new(InterfaceIPStatus)
		**out = **in
	}
}

// DeepCopy creates a deep copy of InterfacesSpec.
func (in *InterfacesSpec) DeepCopy() *InterfacesSpec {
	if in == nil {
		return nil
	}
	out := new(InterfacesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of SrsRanDeploymentStatus into out.
func (in *SrsRanDeploymentStatus) DeepCopyInto(out *SrsRanDeploymentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of SrsRanDeploymentStatus.
func (in *SrsRanDeploymentStatus) DeepCopy() *SrsRanDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(SrsRanDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}
